batch_size: !!python/tuple
- 16
- 256
dropout_rate: !!python/tuple
- 0.0
- 0.5
l2_regularization: !!python/tuple
- 1.0e-06
- 0.01
learning_rate: !!python/tuple
- 0.0001
- 0.1
max_wall_clock_hours: 0.5
model_type: xgboost
n_epochs: !!python/tuple
- 10
- 100
n_trials: 20
preprocessing_config:
  feature_selection: none
  imputation: mean
  scaling: standard
preprocessing_version: v1.0
search_strategy: bayesian
